#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SynAppsFace
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="synapps_iot")]
	public partial class PersonFaceInfoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPersonFaceInfo(PersonFaceInfo instance);
    partial void UpdatePersonFaceInfo(PersonFaceInfo instance);
    partial void DeletePersonFaceInfo(PersonFaceInfo instance);
    #endregion
		
		public PersonFaceInfoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PersonFaceInfoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PersonFaceInfoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PersonFaceInfoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PersonFaceInfo> PersonFaceInfos
		{
			get
			{
				return this.GetTable<PersonFaceInfo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="RBApp.PersonFaceInfo")]
	public partial class PersonFaceInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _PersonId;
		
		private string _FaceConfidence;
		
		private System.Nullable<double> _FaceRectangle_Width;
		
		private System.Nullable<double> _FaceRectangle_Height;
		
		private System.Nullable<double> _FaceRectangle_Left;
		
		private System.Nullable<double> _FaceRectangle_Top;
		
		private System.Nullable<double> _FaceLandmarks_PupilLeft_X;
		
		private System.Nullable<double> _FaceLandmarks_PupilLeft_Y;
		
		private System.Nullable<double> _FaceLandmarks_PupilRight_X;
		
		private System.Nullable<double> _FaceLandmarks_PupilRight_Y;
		
		private System.Nullable<double> _FaceLandmarks_NoseTip_X;
		
		private System.Nullable<double> _FaceLandmarks_NoseTip_Y;
		
		private System.Nullable<double> _FaceLandmarks_MouseLeft_X;
		
		private System.Nullable<double> _FaceLandmarks_MouseLeft_Y;
		
		private System.Nullable<double> _FaceLandmarks_MouseRight_X;
		
		private System.Nullable<double> _FaceLandmarks_MouseRight_Y;
		
		private System.Nullable<double> _FaceLandmarks_EyebrowLeftOuter_X;
		
		private System.Nullable<double> _FaceLandmarks_EyebrowLeftOuter_Y;
		
		private System.Nullable<double> _FaceLandmarks_EyebrowLeftInner_X;
		
		private System.Nullable<double> _FaceLandmarks_EyebrowLeftInner_Y;
		
		private System.Nullable<double> _FaceLandmarks_EyeLeftOuter_X;
		
		private System.Nullable<double> _FaceLandmarks_EyeLeftOuter_Y;
		
		private System.Nullable<double> _FaceLandmarks_EyeLeftTop_X;
		
		private System.Nullable<double> _FaceLandmarks_EyeLeftTop_Y;
		
		private System.Nullable<double> _FaceLandmarks_EyeLeftBottom_X;
		
		private System.Nullable<double> _FaceLandmarks_EyeLeftBottom_Y;
		
		private System.Nullable<double> _FaceLandmarks_EyeLeftInner_X;
		
		private System.Nullable<double> _FaceLandmarks_EyeLeftInner_Y;
		
		private System.Nullable<double> _FaceLandmarks_EyebrowRightInner_X;
		
		private System.Nullable<double> _FaceLandmarks_EyebrowRightInner_Y;
		
		private System.Nullable<double> _FaceLandmarks_EyebrowRightOuter_X;
		
		private System.Nullable<double> _FaceLandmarks_EyebrowRightOuter_Y;
		
		private System.Nullable<double> _FaceLandmarks_EyeRightInner_X;
		
		private System.Nullable<double> _FaceLandmarks_EyeRightInner_Y;
		
		private System.Nullable<double> _FaceLandmarks_EyeRightTop_X;
		
		private System.Nullable<double> _FaceLandmarks_EyeRightTop_Y;
		
		private System.Nullable<double> _FaceLandmarks_EyeRightBottom_X;
		
		private System.Nullable<double> _FaceLandmarks_EyeRightBottom_Y;
		
		private System.Nullable<double> _FaceLandmarks_EyeRightOuter_X;
		
		private System.Nullable<double> _FaceLandmarks_EyeRightOuter_Y;
		
		private System.Nullable<double> _FaceLandmarks_NoseRootLeft_X;
		
		private System.Nullable<double> _FaceLandmarks_NoseRootLeft_Y;
		
		private System.Nullable<double> _FaceLandmarks_NoseRootRight_X;
		
		private System.Nullable<double> _FaceLandmarks_NoseRootRight_Y;
		
		private System.Nullable<double> _FaceLandmarks_NoseLeftAlarTop_X;
		
		private System.Nullable<double> _FaceLandmarks_NoseLeftAlarTop_Y;
		
		private System.Nullable<double> _FaceLandmarks_NoseRightAlarTop_X;
		
		private System.Nullable<double> _FaceLandmarks_NoseRightAlarTop_Y;
		
		private System.Nullable<double> _FaceLandmarks_NoseLeftAlarOutTip_X;
		
		private System.Nullable<double> _FaceLandmarks_NoseLeftAlarOutTip_Y;
		
		private System.Nullable<double> _FaceLandmarks_NoseRightAlarOutTip_X;
		
		private System.Nullable<double> _FaceLandmarks_NoseRightAlarOutTip_Y;
		
		private System.Nullable<double> _FaceLandmarks_UpperLipTop_X;
		
		private System.Nullable<double> _FaceLandmarks_UpperLipTop_Y;
		
		private System.Nullable<double> _FaceLandmarks_UpperLipBottom_X;
		
		private System.Nullable<double> _FaceLandmarks_UpperLipBottom_Y;
		
		private System.Nullable<double> _FaceLandmarks_UnderLipTop_X;
		
		private System.Nullable<double> _FaceLandmarks_UnderLipTop_Y;
		
		private System.Nullable<double> _FaceLandmarks_UnderLipBottom_X;
		
		private System.Nullable<double> _FaceLandmarks_UnderLipBottom_Y;
		
		private System.Nullable<double> _FaceAttributes_Age;
		
		private string _FaceAttributes_Gender;
		
		private System.Nullable<double> _FaceAttributes_Smile;
		
		private System.Nullable<double> _FaceAttributes_FacialHair_Moustache;
		
		private System.Nullable<double> _FaceAttributes_FacialHair_Beard;
		
		private System.Nullable<double> _FaceAttributes_FacialHair_Sideburns;
		
		private string _FaceAttributes_Glasses;
		
		private System.Nullable<double> _FaceAttributes_HeadPose_Roll;
		
		private System.Nullable<double> _FaceAttributes_HeadPose_Yaw;
		
		private System.Nullable<double> _FaceAttributes_HeadPose_Pitch;
		
		private System.Nullable<bool> _IsDeleted;
		
		private System.Nullable<System.DateTime> _CreatedAt;
		
		private System.Nullable<System.DateTime> _UpdatedAt;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnPersonIdChanging(string value);
    partial void OnPersonIdChanged();
    partial void OnFaceConfidenceChanging(string value);
    partial void OnFaceConfidenceChanged();
    partial void OnFaceRectangle_WidthChanging(System.Nullable<double> value);
    partial void OnFaceRectangle_WidthChanged();
    partial void OnFaceRectangle_HeightChanging(System.Nullable<double> value);
    partial void OnFaceRectangle_HeightChanged();
    partial void OnFaceRectangle_LeftChanging(System.Nullable<double> value);
    partial void OnFaceRectangle_LeftChanged();
    partial void OnFaceRectangle_TopChanging(System.Nullable<double> value);
    partial void OnFaceRectangle_TopChanged();
    partial void OnFaceLandmarks_PupilLeft_XChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_PupilLeft_XChanged();
    partial void OnFaceLandmarks_PupilLeft_YChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_PupilLeft_YChanged();
    partial void OnFaceLandmarks_PupilRight_XChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_PupilRight_XChanged();
    partial void OnFaceLandmarks_PupilRight_YChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_PupilRight_YChanged();
    partial void OnFaceLandmarks_NoseTip_XChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_NoseTip_XChanged();
    partial void OnFaceLandmarks_NoseTip_YChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_NoseTip_YChanged();
    partial void OnFaceLandmarks_MouseLeft_XChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_MouseLeft_XChanged();
    partial void OnFaceLandmarks_MouseLeft_YChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_MouseLeft_YChanged();
    partial void OnFaceLandmarks_MouseRight_XChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_MouseRight_XChanged();
    partial void OnFaceLandmarks_MouseRight_YChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_MouseRight_YChanged();
    partial void OnFaceLandmarks_EyebrowLeftOuter_XChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_EyebrowLeftOuter_XChanged();
    partial void OnFaceLandmarks_EyebrowLeftOuter_YChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_EyebrowLeftOuter_YChanged();
    partial void OnFaceLandmarks_EyebrowLeftInner_XChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_EyebrowLeftInner_XChanged();
    partial void OnFaceLandmarks_EyebrowLeftInner_YChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_EyebrowLeftInner_YChanged();
    partial void OnFaceLandmarks_EyeLeftOuter_XChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_EyeLeftOuter_XChanged();
    partial void OnFaceLandmarks_EyeLeftOuter_YChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_EyeLeftOuter_YChanged();
    partial void OnFaceLandmarks_EyeLeftTop_XChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_EyeLeftTop_XChanged();
    partial void OnFaceLandmarks_EyeLeftTop_YChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_EyeLeftTop_YChanged();
    partial void OnFaceLandmarks_EyeLeftBottom_XChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_EyeLeftBottom_XChanged();
    partial void OnFaceLandmarks_EyeLeftBottom_YChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_EyeLeftBottom_YChanged();
    partial void OnFaceLandmarks_EyeLeftInner_XChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_EyeLeftInner_XChanged();
    partial void OnFaceLandmarks_EyeLeftInner_YChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_EyeLeftInner_YChanged();
    partial void OnFaceLandmarks_EyebrowRightInner_XChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_EyebrowRightInner_XChanged();
    partial void OnFaceLandmarks_EyebrowRightInner_YChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_EyebrowRightInner_YChanged();
    partial void OnFaceLandmarks_EyebrowRightOuter_XChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_EyebrowRightOuter_XChanged();
    partial void OnFaceLandmarks_EyebrowRightOuter_YChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_EyebrowRightOuter_YChanged();
    partial void OnFaceLandmarks_EyeRightInner_XChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_EyeRightInner_XChanged();
    partial void OnFaceLandmarks_EyeRightInner_YChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_EyeRightInner_YChanged();
    partial void OnFaceLandmarks_EyeRightTop_XChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_EyeRightTop_XChanged();
    partial void OnFaceLandmarks_EyeRightTop_YChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_EyeRightTop_YChanged();
    partial void OnFaceLandmarks_EyeRightBottom_XChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_EyeRightBottom_XChanged();
    partial void OnFaceLandmarks_EyeRightBottom_YChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_EyeRightBottom_YChanged();
    partial void OnFaceLandmarks_EyeRightOuter_XChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_EyeRightOuter_XChanged();
    partial void OnFaceLandmarks_EyeRightOuter_YChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_EyeRightOuter_YChanged();
    partial void OnFaceLandmarks_NoseRootLeft_XChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_NoseRootLeft_XChanged();
    partial void OnFaceLandmarks_NoseRootLeft_YChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_NoseRootLeft_YChanged();
    partial void OnFaceLandmarks_NoseRootRight_XChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_NoseRootRight_XChanged();
    partial void OnFaceLandmarks_NoseRootRight_YChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_NoseRootRight_YChanged();
    partial void OnFaceLandmarks_NoseLeftAlarTop_XChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_NoseLeftAlarTop_XChanged();
    partial void OnFaceLandmarks_NoseLeftAlarTop_YChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_NoseLeftAlarTop_YChanged();
    partial void OnFaceLandmarks_NoseRightAlarTop_XChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_NoseRightAlarTop_XChanged();
    partial void OnFaceLandmarks_NoseRightAlarTop_YChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_NoseRightAlarTop_YChanged();
    partial void OnFaceLandmarks_NoseLeftAlarOutTip_XChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_NoseLeftAlarOutTip_XChanged();
    partial void OnFaceLandmarks_NoseLeftAlarOutTip_YChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_NoseLeftAlarOutTip_YChanged();
    partial void OnFaceLandmarks_NoseRightAlarOutTip_XChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_NoseRightAlarOutTip_XChanged();
    partial void OnFaceLandmarks_NoseRightAlarOutTip_YChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_NoseRightAlarOutTip_YChanged();
    partial void OnFaceLandmarks_UpperLipTop_XChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_UpperLipTop_XChanged();
    partial void OnFaceLandmarks_UpperLipTop_YChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_UpperLipTop_YChanged();
    partial void OnFaceLandmarks_UpperLipBottom_XChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_UpperLipBottom_XChanged();
    partial void OnFaceLandmarks_UpperLipBottom_YChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_UpperLipBottom_YChanged();
    partial void OnFaceLandmarks_UnderLipTop_XChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_UnderLipTop_XChanged();
    partial void OnFaceLandmarks_UnderLipTop_YChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_UnderLipTop_YChanged();
    partial void OnFaceLandmarks_UnderLipBottom_XChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_UnderLipBottom_XChanged();
    partial void OnFaceLandmarks_UnderLipBottom_YChanging(System.Nullable<double> value);
    partial void OnFaceLandmarks_UnderLipBottom_YChanged();
    partial void OnFaceAttributes_AgeChanging(System.Nullable<double> value);
    partial void OnFaceAttributes_AgeChanged();
    partial void OnFaceAttributes_GenderChanging(string value);
    partial void OnFaceAttributes_GenderChanged();
    partial void OnFaceAttributes_SmileChanging(System.Nullable<double> value);
    partial void OnFaceAttributes_SmileChanged();
    partial void OnFaceAttributes_FacialHair_MoustacheChanging(System.Nullable<double> value);
    partial void OnFaceAttributes_FacialHair_MoustacheChanged();
    partial void OnFaceAttributes_FacialHair_BeardChanging(System.Nullable<double> value);
    partial void OnFaceAttributes_FacialHair_BeardChanged();
    partial void OnFaceAttributes_FacialHair_SideburnsChanging(System.Nullable<double> value);
    partial void OnFaceAttributes_FacialHair_SideburnsChanged();
    partial void OnFaceAttributes_GlassesChanging(string value);
    partial void OnFaceAttributes_GlassesChanged();
    partial void OnFaceAttributes_HeadPose_RollChanging(System.Nullable<double> value);
    partial void OnFaceAttributes_HeadPose_RollChanged();
    partial void OnFaceAttributes_HeadPose_YawChanging(System.Nullable<double> value);
    partial void OnFaceAttributes_HeadPose_YawChanged();
    partial void OnFaceAttributes_HeadPose_PitchChanging(System.Nullable<double> value);
    partial void OnFaceAttributes_HeadPose_PitchChanged();
    partial void OnIsDeletedChanging(System.Nullable<bool> value);
    partial void OnIsDeletedChanged();
    partial void OnCreatedAtChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedAtChanged();
    partial void OnUpdatedAtChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdatedAtChanged();
    #endregion
		
		public PersonFaceInfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonId", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string PersonId
		{
			get
			{
				return this._PersonId;
			}
			set
			{
				if ((this._PersonId != value))
				{
					this.OnPersonIdChanging(value);
					this.SendPropertyChanging();
					this._PersonId = value;
					this.SendPropertyChanged("PersonId");
					this.OnPersonIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceConfidence", DbType="NVarChar(40)")]
		public string FaceConfidence
		{
			get
			{
				return this._FaceConfidence;
			}
			set
			{
				if ((this._FaceConfidence != value))
				{
					this.OnFaceConfidenceChanging(value);
					this.SendPropertyChanging();
					this._FaceConfidence = value;
					this.SendPropertyChanged("FaceConfidence");
					this.OnFaceConfidenceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceRectangle_Width", DbType="Float")]
		public System.Nullable<double> FaceRectangle_Width
		{
			get
			{
				return this._FaceRectangle_Width;
			}
			set
			{
				if ((this._FaceRectangle_Width != value))
				{
					this.OnFaceRectangle_WidthChanging(value);
					this.SendPropertyChanging();
					this._FaceRectangle_Width = value;
					this.SendPropertyChanged("FaceRectangle_Width");
					this.OnFaceRectangle_WidthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceRectangle_Height", DbType="Float")]
		public System.Nullable<double> FaceRectangle_Height
		{
			get
			{
				return this._FaceRectangle_Height;
			}
			set
			{
				if ((this._FaceRectangle_Height != value))
				{
					this.OnFaceRectangle_HeightChanging(value);
					this.SendPropertyChanging();
					this._FaceRectangle_Height = value;
					this.SendPropertyChanged("FaceRectangle_Height");
					this.OnFaceRectangle_HeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceRectangle_Left", DbType="Float")]
		public System.Nullable<double> FaceRectangle_Left
		{
			get
			{
				return this._FaceRectangle_Left;
			}
			set
			{
				if ((this._FaceRectangle_Left != value))
				{
					this.OnFaceRectangle_LeftChanging(value);
					this.SendPropertyChanging();
					this._FaceRectangle_Left = value;
					this.SendPropertyChanged("FaceRectangle_Left");
					this.OnFaceRectangle_LeftChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceRectangle_Top", DbType="Float")]
		public System.Nullable<double> FaceRectangle_Top
		{
			get
			{
				return this._FaceRectangle_Top;
			}
			set
			{
				if ((this._FaceRectangle_Top != value))
				{
					this.OnFaceRectangle_TopChanging(value);
					this.SendPropertyChanging();
					this._FaceRectangle_Top = value;
					this.SendPropertyChanged("FaceRectangle_Top");
					this.OnFaceRectangle_TopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_PupilLeft_X", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_PupilLeft_X
		{
			get
			{
				return this._FaceLandmarks_PupilLeft_X;
			}
			set
			{
				if ((this._FaceLandmarks_PupilLeft_X != value))
				{
					this.OnFaceLandmarks_PupilLeft_XChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_PupilLeft_X = value;
					this.SendPropertyChanged("FaceLandmarks_PupilLeft_X");
					this.OnFaceLandmarks_PupilLeft_XChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_PupilLeft_Y", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_PupilLeft_Y
		{
			get
			{
				return this._FaceLandmarks_PupilLeft_Y;
			}
			set
			{
				if ((this._FaceLandmarks_PupilLeft_Y != value))
				{
					this.OnFaceLandmarks_PupilLeft_YChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_PupilLeft_Y = value;
					this.SendPropertyChanged("FaceLandmarks_PupilLeft_Y");
					this.OnFaceLandmarks_PupilLeft_YChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_PupilRight_X", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_PupilRight_X
		{
			get
			{
				return this._FaceLandmarks_PupilRight_X;
			}
			set
			{
				if ((this._FaceLandmarks_PupilRight_X != value))
				{
					this.OnFaceLandmarks_PupilRight_XChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_PupilRight_X = value;
					this.SendPropertyChanged("FaceLandmarks_PupilRight_X");
					this.OnFaceLandmarks_PupilRight_XChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_PupilRight_Y", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_PupilRight_Y
		{
			get
			{
				return this._FaceLandmarks_PupilRight_Y;
			}
			set
			{
				if ((this._FaceLandmarks_PupilRight_Y != value))
				{
					this.OnFaceLandmarks_PupilRight_YChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_PupilRight_Y = value;
					this.SendPropertyChanged("FaceLandmarks_PupilRight_Y");
					this.OnFaceLandmarks_PupilRight_YChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_NoseTip_X", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_NoseTip_X
		{
			get
			{
				return this._FaceLandmarks_NoseTip_X;
			}
			set
			{
				if ((this._FaceLandmarks_NoseTip_X != value))
				{
					this.OnFaceLandmarks_NoseTip_XChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_NoseTip_X = value;
					this.SendPropertyChanged("FaceLandmarks_NoseTip_X");
					this.OnFaceLandmarks_NoseTip_XChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_NoseTip_Y", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_NoseTip_Y
		{
			get
			{
				return this._FaceLandmarks_NoseTip_Y;
			}
			set
			{
				if ((this._FaceLandmarks_NoseTip_Y != value))
				{
					this.OnFaceLandmarks_NoseTip_YChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_NoseTip_Y = value;
					this.SendPropertyChanged("FaceLandmarks_NoseTip_Y");
					this.OnFaceLandmarks_NoseTip_YChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_MouseLeft_X", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_MouseLeft_X
		{
			get
			{
				return this._FaceLandmarks_MouseLeft_X;
			}
			set
			{
				if ((this._FaceLandmarks_MouseLeft_X != value))
				{
					this.OnFaceLandmarks_MouseLeft_XChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_MouseLeft_X = value;
					this.SendPropertyChanged("FaceLandmarks_MouseLeft_X");
					this.OnFaceLandmarks_MouseLeft_XChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_MouseLeft_Y", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_MouseLeft_Y
		{
			get
			{
				return this._FaceLandmarks_MouseLeft_Y;
			}
			set
			{
				if ((this._FaceLandmarks_MouseLeft_Y != value))
				{
					this.OnFaceLandmarks_MouseLeft_YChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_MouseLeft_Y = value;
					this.SendPropertyChanged("FaceLandmarks_MouseLeft_Y");
					this.OnFaceLandmarks_MouseLeft_YChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_MouseRight_X", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_MouseRight_X
		{
			get
			{
				return this._FaceLandmarks_MouseRight_X;
			}
			set
			{
				if ((this._FaceLandmarks_MouseRight_X != value))
				{
					this.OnFaceLandmarks_MouseRight_XChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_MouseRight_X = value;
					this.SendPropertyChanged("FaceLandmarks_MouseRight_X");
					this.OnFaceLandmarks_MouseRight_XChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_MouseRight_Y", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_MouseRight_Y
		{
			get
			{
				return this._FaceLandmarks_MouseRight_Y;
			}
			set
			{
				if ((this._FaceLandmarks_MouseRight_Y != value))
				{
					this.OnFaceLandmarks_MouseRight_YChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_MouseRight_Y = value;
					this.SendPropertyChanged("FaceLandmarks_MouseRight_Y");
					this.OnFaceLandmarks_MouseRight_YChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_EyebrowLeftOuter_X", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_EyebrowLeftOuter_X
		{
			get
			{
				return this._FaceLandmarks_EyebrowLeftOuter_X;
			}
			set
			{
				if ((this._FaceLandmarks_EyebrowLeftOuter_X != value))
				{
					this.OnFaceLandmarks_EyebrowLeftOuter_XChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_EyebrowLeftOuter_X = value;
					this.SendPropertyChanged("FaceLandmarks_EyebrowLeftOuter_X");
					this.OnFaceLandmarks_EyebrowLeftOuter_XChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_EyebrowLeftOuter_Y", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_EyebrowLeftOuter_Y
		{
			get
			{
				return this._FaceLandmarks_EyebrowLeftOuter_Y;
			}
			set
			{
				if ((this._FaceLandmarks_EyebrowLeftOuter_Y != value))
				{
					this.OnFaceLandmarks_EyebrowLeftOuter_YChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_EyebrowLeftOuter_Y = value;
					this.SendPropertyChanged("FaceLandmarks_EyebrowLeftOuter_Y");
					this.OnFaceLandmarks_EyebrowLeftOuter_YChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_EyebrowLeftInner_X", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_EyebrowLeftInner_X
		{
			get
			{
				return this._FaceLandmarks_EyebrowLeftInner_X;
			}
			set
			{
				if ((this._FaceLandmarks_EyebrowLeftInner_X != value))
				{
					this.OnFaceLandmarks_EyebrowLeftInner_XChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_EyebrowLeftInner_X = value;
					this.SendPropertyChanged("FaceLandmarks_EyebrowLeftInner_X");
					this.OnFaceLandmarks_EyebrowLeftInner_XChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_EyebrowLeftInner_Y", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_EyebrowLeftInner_Y
		{
			get
			{
				return this._FaceLandmarks_EyebrowLeftInner_Y;
			}
			set
			{
				if ((this._FaceLandmarks_EyebrowLeftInner_Y != value))
				{
					this.OnFaceLandmarks_EyebrowLeftInner_YChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_EyebrowLeftInner_Y = value;
					this.SendPropertyChanged("FaceLandmarks_EyebrowLeftInner_Y");
					this.OnFaceLandmarks_EyebrowLeftInner_YChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_EyeLeftOuter_X", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_EyeLeftOuter_X
		{
			get
			{
				return this._FaceLandmarks_EyeLeftOuter_X;
			}
			set
			{
				if ((this._FaceLandmarks_EyeLeftOuter_X != value))
				{
					this.OnFaceLandmarks_EyeLeftOuter_XChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_EyeLeftOuter_X = value;
					this.SendPropertyChanged("FaceLandmarks_EyeLeftOuter_X");
					this.OnFaceLandmarks_EyeLeftOuter_XChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_EyeLeftOuter_Y", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_EyeLeftOuter_Y
		{
			get
			{
				return this._FaceLandmarks_EyeLeftOuter_Y;
			}
			set
			{
				if ((this._FaceLandmarks_EyeLeftOuter_Y != value))
				{
					this.OnFaceLandmarks_EyeLeftOuter_YChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_EyeLeftOuter_Y = value;
					this.SendPropertyChanged("FaceLandmarks_EyeLeftOuter_Y");
					this.OnFaceLandmarks_EyeLeftOuter_YChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_EyeLeftTop_X", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_EyeLeftTop_X
		{
			get
			{
				return this._FaceLandmarks_EyeLeftTop_X;
			}
			set
			{
				if ((this._FaceLandmarks_EyeLeftTop_X != value))
				{
					this.OnFaceLandmarks_EyeLeftTop_XChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_EyeLeftTop_X = value;
					this.SendPropertyChanged("FaceLandmarks_EyeLeftTop_X");
					this.OnFaceLandmarks_EyeLeftTop_XChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_EyeLeftTop_Y", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_EyeLeftTop_Y
		{
			get
			{
				return this._FaceLandmarks_EyeLeftTop_Y;
			}
			set
			{
				if ((this._FaceLandmarks_EyeLeftTop_Y != value))
				{
					this.OnFaceLandmarks_EyeLeftTop_YChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_EyeLeftTop_Y = value;
					this.SendPropertyChanged("FaceLandmarks_EyeLeftTop_Y");
					this.OnFaceLandmarks_EyeLeftTop_YChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_EyeLeftBottom_X", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_EyeLeftBottom_X
		{
			get
			{
				return this._FaceLandmarks_EyeLeftBottom_X;
			}
			set
			{
				if ((this._FaceLandmarks_EyeLeftBottom_X != value))
				{
					this.OnFaceLandmarks_EyeLeftBottom_XChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_EyeLeftBottom_X = value;
					this.SendPropertyChanged("FaceLandmarks_EyeLeftBottom_X");
					this.OnFaceLandmarks_EyeLeftBottom_XChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_EyeLeftBottom_Y", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_EyeLeftBottom_Y
		{
			get
			{
				return this._FaceLandmarks_EyeLeftBottom_Y;
			}
			set
			{
				if ((this._FaceLandmarks_EyeLeftBottom_Y != value))
				{
					this.OnFaceLandmarks_EyeLeftBottom_YChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_EyeLeftBottom_Y = value;
					this.SendPropertyChanged("FaceLandmarks_EyeLeftBottom_Y");
					this.OnFaceLandmarks_EyeLeftBottom_YChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_EyeLeftInner_X", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_EyeLeftInner_X
		{
			get
			{
				return this._FaceLandmarks_EyeLeftInner_X;
			}
			set
			{
				if ((this._FaceLandmarks_EyeLeftInner_X != value))
				{
					this.OnFaceLandmarks_EyeLeftInner_XChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_EyeLeftInner_X = value;
					this.SendPropertyChanged("FaceLandmarks_EyeLeftInner_X");
					this.OnFaceLandmarks_EyeLeftInner_XChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_EyeLeftInner_Y", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_EyeLeftInner_Y
		{
			get
			{
				return this._FaceLandmarks_EyeLeftInner_Y;
			}
			set
			{
				if ((this._FaceLandmarks_EyeLeftInner_Y != value))
				{
					this.OnFaceLandmarks_EyeLeftInner_YChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_EyeLeftInner_Y = value;
					this.SendPropertyChanged("FaceLandmarks_EyeLeftInner_Y");
					this.OnFaceLandmarks_EyeLeftInner_YChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_EyebrowRightInner_X", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_EyebrowRightInner_X
		{
			get
			{
				return this._FaceLandmarks_EyebrowRightInner_X;
			}
			set
			{
				if ((this._FaceLandmarks_EyebrowRightInner_X != value))
				{
					this.OnFaceLandmarks_EyebrowRightInner_XChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_EyebrowRightInner_X = value;
					this.SendPropertyChanged("FaceLandmarks_EyebrowRightInner_X");
					this.OnFaceLandmarks_EyebrowRightInner_XChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_EyebrowRightInner_Y", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_EyebrowRightInner_Y
		{
			get
			{
				return this._FaceLandmarks_EyebrowRightInner_Y;
			}
			set
			{
				if ((this._FaceLandmarks_EyebrowRightInner_Y != value))
				{
					this.OnFaceLandmarks_EyebrowRightInner_YChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_EyebrowRightInner_Y = value;
					this.SendPropertyChanged("FaceLandmarks_EyebrowRightInner_Y");
					this.OnFaceLandmarks_EyebrowRightInner_YChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_EyebrowRightOuter_X", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_EyebrowRightOuter_X
		{
			get
			{
				return this._FaceLandmarks_EyebrowRightOuter_X;
			}
			set
			{
				if ((this._FaceLandmarks_EyebrowRightOuter_X != value))
				{
					this.OnFaceLandmarks_EyebrowRightOuter_XChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_EyebrowRightOuter_X = value;
					this.SendPropertyChanged("FaceLandmarks_EyebrowRightOuter_X");
					this.OnFaceLandmarks_EyebrowRightOuter_XChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_EyebrowRightOuter_Y", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_EyebrowRightOuter_Y
		{
			get
			{
				return this._FaceLandmarks_EyebrowRightOuter_Y;
			}
			set
			{
				if ((this._FaceLandmarks_EyebrowRightOuter_Y != value))
				{
					this.OnFaceLandmarks_EyebrowRightOuter_YChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_EyebrowRightOuter_Y = value;
					this.SendPropertyChanged("FaceLandmarks_EyebrowRightOuter_Y");
					this.OnFaceLandmarks_EyebrowRightOuter_YChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_EyeRightInner_X", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_EyeRightInner_X
		{
			get
			{
				return this._FaceLandmarks_EyeRightInner_X;
			}
			set
			{
				if ((this._FaceLandmarks_EyeRightInner_X != value))
				{
					this.OnFaceLandmarks_EyeRightInner_XChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_EyeRightInner_X = value;
					this.SendPropertyChanged("FaceLandmarks_EyeRightInner_X");
					this.OnFaceLandmarks_EyeRightInner_XChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_EyeRightInner_Y", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_EyeRightInner_Y
		{
			get
			{
				return this._FaceLandmarks_EyeRightInner_Y;
			}
			set
			{
				if ((this._FaceLandmarks_EyeRightInner_Y != value))
				{
					this.OnFaceLandmarks_EyeRightInner_YChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_EyeRightInner_Y = value;
					this.SendPropertyChanged("FaceLandmarks_EyeRightInner_Y");
					this.OnFaceLandmarks_EyeRightInner_YChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_EyeRightTop_X", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_EyeRightTop_X
		{
			get
			{
				return this._FaceLandmarks_EyeRightTop_X;
			}
			set
			{
				if ((this._FaceLandmarks_EyeRightTop_X != value))
				{
					this.OnFaceLandmarks_EyeRightTop_XChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_EyeRightTop_X = value;
					this.SendPropertyChanged("FaceLandmarks_EyeRightTop_X");
					this.OnFaceLandmarks_EyeRightTop_XChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_EyeRightTop_Y", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_EyeRightTop_Y
		{
			get
			{
				return this._FaceLandmarks_EyeRightTop_Y;
			}
			set
			{
				if ((this._FaceLandmarks_EyeRightTop_Y != value))
				{
					this.OnFaceLandmarks_EyeRightTop_YChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_EyeRightTop_Y = value;
					this.SendPropertyChanged("FaceLandmarks_EyeRightTop_Y");
					this.OnFaceLandmarks_EyeRightTop_YChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_EyeRightBottom_X", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_EyeRightBottom_X
		{
			get
			{
				return this._FaceLandmarks_EyeRightBottom_X;
			}
			set
			{
				if ((this._FaceLandmarks_EyeRightBottom_X != value))
				{
					this.OnFaceLandmarks_EyeRightBottom_XChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_EyeRightBottom_X = value;
					this.SendPropertyChanged("FaceLandmarks_EyeRightBottom_X");
					this.OnFaceLandmarks_EyeRightBottom_XChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_EyeRightBottom_Y", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_EyeRightBottom_Y
		{
			get
			{
				return this._FaceLandmarks_EyeRightBottom_Y;
			}
			set
			{
				if ((this._FaceLandmarks_EyeRightBottom_Y != value))
				{
					this.OnFaceLandmarks_EyeRightBottom_YChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_EyeRightBottom_Y = value;
					this.SendPropertyChanged("FaceLandmarks_EyeRightBottom_Y");
					this.OnFaceLandmarks_EyeRightBottom_YChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_EyeRightOuter_X", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_EyeRightOuter_X
		{
			get
			{
				return this._FaceLandmarks_EyeRightOuter_X;
			}
			set
			{
				if ((this._FaceLandmarks_EyeRightOuter_X != value))
				{
					this.OnFaceLandmarks_EyeRightOuter_XChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_EyeRightOuter_X = value;
					this.SendPropertyChanged("FaceLandmarks_EyeRightOuter_X");
					this.OnFaceLandmarks_EyeRightOuter_XChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_EyeRightOuter_Y", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_EyeRightOuter_Y
		{
			get
			{
				return this._FaceLandmarks_EyeRightOuter_Y;
			}
			set
			{
				if ((this._FaceLandmarks_EyeRightOuter_Y != value))
				{
					this.OnFaceLandmarks_EyeRightOuter_YChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_EyeRightOuter_Y = value;
					this.SendPropertyChanged("FaceLandmarks_EyeRightOuter_Y");
					this.OnFaceLandmarks_EyeRightOuter_YChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_NoseRootLeft_X", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_NoseRootLeft_X
		{
			get
			{
				return this._FaceLandmarks_NoseRootLeft_X;
			}
			set
			{
				if ((this._FaceLandmarks_NoseRootLeft_X != value))
				{
					this.OnFaceLandmarks_NoseRootLeft_XChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_NoseRootLeft_X = value;
					this.SendPropertyChanged("FaceLandmarks_NoseRootLeft_X");
					this.OnFaceLandmarks_NoseRootLeft_XChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_NoseRootLeft_Y", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_NoseRootLeft_Y
		{
			get
			{
				return this._FaceLandmarks_NoseRootLeft_Y;
			}
			set
			{
				if ((this._FaceLandmarks_NoseRootLeft_Y != value))
				{
					this.OnFaceLandmarks_NoseRootLeft_YChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_NoseRootLeft_Y = value;
					this.SendPropertyChanged("FaceLandmarks_NoseRootLeft_Y");
					this.OnFaceLandmarks_NoseRootLeft_YChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_NoseRootRight_X", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_NoseRootRight_X
		{
			get
			{
				return this._FaceLandmarks_NoseRootRight_X;
			}
			set
			{
				if ((this._FaceLandmarks_NoseRootRight_X != value))
				{
					this.OnFaceLandmarks_NoseRootRight_XChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_NoseRootRight_X = value;
					this.SendPropertyChanged("FaceLandmarks_NoseRootRight_X");
					this.OnFaceLandmarks_NoseRootRight_XChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_NoseRootRight_Y", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_NoseRootRight_Y
		{
			get
			{
				return this._FaceLandmarks_NoseRootRight_Y;
			}
			set
			{
				if ((this._FaceLandmarks_NoseRootRight_Y != value))
				{
					this.OnFaceLandmarks_NoseRootRight_YChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_NoseRootRight_Y = value;
					this.SendPropertyChanged("FaceLandmarks_NoseRootRight_Y");
					this.OnFaceLandmarks_NoseRootRight_YChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_NoseLeftAlarTop_X", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_NoseLeftAlarTop_X
		{
			get
			{
				return this._FaceLandmarks_NoseLeftAlarTop_X;
			}
			set
			{
				if ((this._FaceLandmarks_NoseLeftAlarTop_X != value))
				{
					this.OnFaceLandmarks_NoseLeftAlarTop_XChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_NoseLeftAlarTop_X = value;
					this.SendPropertyChanged("FaceLandmarks_NoseLeftAlarTop_X");
					this.OnFaceLandmarks_NoseLeftAlarTop_XChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_NoseLeftAlarTop_Y", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_NoseLeftAlarTop_Y
		{
			get
			{
				return this._FaceLandmarks_NoseLeftAlarTop_Y;
			}
			set
			{
				if ((this._FaceLandmarks_NoseLeftAlarTop_Y != value))
				{
					this.OnFaceLandmarks_NoseLeftAlarTop_YChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_NoseLeftAlarTop_Y = value;
					this.SendPropertyChanged("FaceLandmarks_NoseLeftAlarTop_Y");
					this.OnFaceLandmarks_NoseLeftAlarTop_YChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_NoseRightAlarTop_X", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_NoseRightAlarTop_X
		{
			get
			{
				return this._FaceLandmarks_NoseRightAlarTop_X;
			}
			set
			{
				if ((this._FaceLandmarks_NoseRightAlarTop_X != value))
				{
					this.OnFaceLandmarks_NoseRightAlarTop_XChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_NoseRightAlarTop_X = value;
					this.SendPropertyChanged("FaceLandmarks_NoseRightAlarTop_X");
					this.OnFaceLandmarks_NoseRightAlarTop_XChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_NoseRightAlarTop_Y", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_NoseRightAlarTop_Y
		{
			get
			{
				return this._FaceLandmarks_NoseRightAlarTop_Y;
			}
			set
			{
				if ((this._FaceLandmarks_NoseRightAlarTop_Y != value))
				{
					this.OnFaceLandmarks_NoseRightAlarTop_YChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_NoseRightAlarTop_Y = value;
					this.SendPropertyChanged("FaceLandmarks_NoseRightAlarTop_Y");
					this.OnFaceLandmarks_NoseRightAlarTop_YChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_NoseLeftAlarOutTip_X", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_NoseLeftAlarOutTip_X
		{
			get
			{
				return this._FaceLandmarks_NoseLeftAlarOutTip_X;
			}
			set
			{
				if ((this._FaceLandmarks_NoseLeftAlarOutTip_X != value))
				{
					this.OnFaceLandmarks_NoseLeftAlarOutTip_XChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_NoseLeftAlarOutTip_X = value;
					this.SendPropertyChanged("FaceLandmarks_NoseLeftAlarOutTip_X");
					this.OnFaceLandmarks_NoseLeftAlarOutTip_XChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_NoseLeftAlarOutTip_Y", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_NoseLeftAlarOutTip_Y
		{
			get
			{
				return this._FaceLandmarks_NoseLeftAlarOutTip_Y;
			}
			set
			{
				if ((this._FaceLandmarks_NoseLeftAlarOutTip_Y != value))
				{
					this.OnFaceLandmarks_NoseLeftAlarOutTip_YChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_NoseLeftAlarOutTip_Y = value;
					this.SendPropertyChanged("FaceLandmarks_NoseLeftAlarOutTip_Y");
					this.OnFaceLandmarks_NoseLeftAlarOutTip_YChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_NoseRightAlarOutTip_X", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_NoseRightAlarOutTip_X
		{
			get
			{
				return this._FaceLandmarks_NoseRightAlarOutTip_X;
			}
			set
			{
				if ((this._FaceLandmarks_NoseRightAlarOutTip_X != value))
				{
					this.OnFaceLandmarks_NoseRightAlarOutTip_XChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_NoseRightAlarOutTip_X = value;
					this.SendPropertyChanged("FaceLandmarks_NoseRightAlarOutTip_X");
					this.OnFaceLandmarks_NoseRightAlarOutTip_XChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_NoseRightAlarOutTip_Y", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_NoseRightAlarOutTip_Y
		{
			get
			{
				return this._FaceLandmarks_NoseRightAlarOutTip_Y;
			}
			set
			{
				if ((this._FaceLandmarks_NoseRightAlarOutTip_Y != value))
				{
					this.OnFaceLandmarks_NoseRightAlarOutTip_YChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_NoseRightAlarOutTip_Y = value;
					this.SendPropertyChanged("FaceLandmarks_NoseRightAlarOutTip_Y");
					this.OnFaceLandmarks_NoseRightAlarOutTip_YChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_UpperLipTop_X", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_UpperLipTop_X
		{
			get
			{
				return this._FaceLandmarks_UpperLipTop_X;
			}
			set
			{
				if ((this._FaceLandmarks_UpperLipTop_X != value))
				{
					this.OnFaceLandmarks_UpperLipTop_XChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_UpperLipTop_X = value;
					this.SendPropertyChanged("FaceLandmarks_UpperLipTop_X");
					this.OnFaceLandmarks_UpperLipTop_XChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_UpperLipTop_Y", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_UpperLipTop_Y
		{
			get
			{
				return this._FaceLandmarks_UpperLipTop_Y;
			}
			set
			{
				if ((this._FaceLandmarks_UpperLipTop_Y != value))
				{
					this.OnFaceLandmarks_UpperLipTop_YChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_UpperLipTop_Y = value;
					this.SendPropertyChanged("FaceLandmarks_UpperLipTop_Y");
					this.OnFaceLandmarks_UpperLipTop_YChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_UpperLipBottom_X", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_UpperLipBottom_X
		{
			get
			{
				return this._FaceLandmarks_UpperLipBottom_X;
			}
			set
			{
				if ((this._FaceLandmarks_UpperLipBottom_X != value))
				{
					this.OnFaceLandmarks_UpperLipBottom_XChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_UpperLipBottom_X = value;
					this.SendPropertyChanged("FaceLandmarks_UpperLipBottom_X");
					this.OnFaceLandmarks_UpperLipBottom_XChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_UpperLipBottom_Y", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_UpperLipBottom_Y
		{
			get
			{
				return this._FaceLandmarks_UpperLipBottom_Y;
			}
			set
			{
				if ((this._FaceLandmarks_UpperLipBottom_Y != value))
				{
					this.OnFaceLandmarks_UpperLipBottom_YChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_UpperLipBottom_Y = value;
					this.SendPropertyChanged("FaceLandmarks_UpperLipBottom_Y");
					this.OnFaceLandmarks_UpperLipBottom_YChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_UnderLipTop_X", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_UnderLipTop_X
		{
			get
			{
				return this._FaceLandmarks_UnderLipTop_X;
			}
			set
			{
				if ((this._FaceLandmarks_UnderLipTop_X != value))
				{
					this.OnFaceLandmarks_UnderLipTop_XChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_UnderLipTop_X = value;
					this.SendPropertyChanged("FaceLandmarks_UnderLipTop_X");
					this.OnFaceLandmarks_UnderLipTop_XChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_UnderLipTop_Y", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_UnderLipTop_Y
		{
			get
			{
				return this._FaceLandmarks_UnderLipTop_Y;
			}
			set
			{
				if ((this._FaceLandmarks_UnderLipTop_Y != value))
				{
					this.OnFaceLandmarks_UnderLipTop_YChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_UnderLipTop_Y = value;
					this.SendPropertyChanged("FaceLandmarks_UnderLipTop_Y");
					this.OnFaceLandmarks_UnderLipTop_YChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_UnderLipBottom_X", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_UnderLipBottom_X
		{
			get
			{
				return this._FaceLandmarks_UnderLipBottom_X;
			}
			set
			{
				if ((this._FaceLandmarks_UnderLipBottom_X != value))
				{
					this.OnFaceLandmarks_UnderLipBottom_XChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_UnderLipBottom_X = value;
					this.SendPropertyChanged("FaceLandmarks_UnderLipBottom_X");
					this.OnFaceLandmarks_UnderLipBottom_XChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceLandmarks_UnderLipBottom_Y", DbType="Float")]
		public System.Nullable<double> FaceLandmarks_UnderLipBottom_Y
		{
			get
			{
				return this._FaceLandmarks_UnderLipBottom_Y;
			}
			set
			{
				if ((this._FaceLandmarks_UnderLipBottom_Y != value))
				{
					this.OnFaceLandmarks_UnderLipBottom_YChanging(value);
					this.SendPropertyChanging();
					this._FaceLandmarks_UnderLipBottom_Y = value;
					this.SendPropertyChanged("FaceLandmarks_UnderLipBottom_Y");
					this.OnFaceLandmarks_UnderLipBottom_YChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceAttributes_Age", DbType="Float")]
		public System.Nullable<double> FaceAttributes_Age
		{
			get
			{
				return this._FaceAttributes_Age;
			}
			set
			{
				if ((this._FaceAttributes_Age != value))
				{
					this.OnFaceAttributes_AgeChanging(value);
					this.SendPropertyChanging();
					this._FaceAttributes_Age = value;
					this.SendPropertyChanged("FaceAttributes_Age");
					this.OnFaceAttributes_AgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceAttributes_Gender", DbType="NVarChar(10)")]
		public string FaceAttributes_Gender
		{
			get
			{
				return this._FaceAttributes_Gender;
			}
			set
			{
				if ((this._FaceAttributes_Gender != value))
				{
					this.OnFaceAttributes_GenderChanging(value);
					this.SendPropertyChanging();
					this._FaceAttributes_Gender = value;
					this.SendPropertyChanged("FaceAttributes_Gender");
					this.OnFaceAttributes_GenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceAttributes_Smile", DbType="Float")]
		public System.Nullable<double> FaceAttributes_Smile
		{
			get
			{
				return this._FaceAttributes_Smile;
			}
			set
			{
				if ((this._FaceAttributes_Smile != value))
				{
					this.OnFaceAttributes_SmileChanging(value);
					this.SendPropertyChanging();
					this._FaceAttributes_Smile = value;
					this.SendPropertyChanged("FaceAttributes_Smile");
					this.OnFaceAttributes_SmileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceAttributes_FacialHair_Moustache", DbType="Float")]
		public System.Nullable<double> FaceAttributes_FacialHair_Moustache
		{
			get
			{
				return this._FaceAttributes_FacialHair_Moustache;
			}
			set
			{
				if ((this._FaceAttributes_FacialHair_Moustache != value))
				{
					this.OnFaceAttributes_FacialHair_MoustacheChanging(value);
					this.SendPropertyChanging();
					this._FaceAttributes_FacialHair_Moustache = value;
					this.SendPropertyChanged("FaceAttributes_FacialHair_Moustache");
					this.OnFaceAttributes_FacialHair_MoustacheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceAttributes_FacialHair_Beard", DbType="Float")]
		public System.Nullable<double> FaceAttributes_FacialHair_Beard
		{
			get
			{
				return this._FaceAttributes_FacialHair_Beard;
			}
			set
			{
				if ((this._FaceAttributes_FacialHair_Beard != value))
				{
					this.OnFaceAttributes_FacialHair_BeardChanging(value);
					this.SendPropertyChanging();
					this._FaceAttributes_FacialHair_Beard = value;
					this.SendPropertyChanged("FaceAttributes_FacialHair_Beard");
					this.OnFaceAttributes_FacialHair_BeardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceAttributes_FacialHair_Sideburns", DbType="Float")]
		public System.Nullable<double> FaceAttributes_FacialHair_Sideburns
		{
			get
			{
				return this._FaceAttributes_FacialHair_Sideburns;
			}
			set
			{
				if ((this._FaceAttributes_FacialHair_Sideburns != value))
				{
					this.OnFaceAttributes_FacialHair_SideburnsChanging(value);
					this.SendPropertyChanging();
					this._FaceAttributes_FacialHair_Sideburns = value;
					this.SendPropertyChanged("FaceAttributes_FacialHair_Sideburns");
					this.OnFaceAttributes_FacialHair_SideburnsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceAttributes_Glasses", DbType="NVarChar(20)")]
		public string FaceAttributes_Glasses
		{
			get
			{
				return this._FaceAttributes_Glasses;
			}
			set
			{
				if ((this._FaceAttributes_Glasses != value))
				{
					this.OnFaceAttributes_GlassesChanging(value);
					this.SendPropertyChanging();
					this._FaceAttributes_Glasses = value;
					this.SendPropertyChanged("FaceAttributes_Glasses");
					this.OnFaceAttributes_GlassesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceAttributes_HeadPose_Roll", DbType="Float")]
		public System.Nullable<double> FaceAttributes_HeadPose_Roll
		{
			get
			{
				return this._FaceAttributes_HeadPose_Roll;
			}
			set
			{
				if ((this._FaceAttributes_HeadPose_Roll != value))
				{
					this.OnFaceAttributes_HeadPose_RollChanging(value);
					this.SendPropertyChanging();
					this._FaceAttributes_HeadPose_Roll = value;
					this.SendPropertyChanged("FaceAttributes_HeadPose_Roll");
					this.OnFaceAttributes_HeadPose_RollChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceAttributes_HeadPose_Yaw", DbType="Float")]
		public System.Nullable<double> FaceAttributes_HeadPose_Yaw
		{
			get
			{
				return this._FaceAttributes_HeadPose_Yaw;
			}
			set
			{
				if ((this._FaceAttributes_HeadPose_Yaw != value))
				{
					this.OnFaceAttributes_HeadPose_YawChanging(value);
					this.SendPropertyChanging();
					this._FaceAttributes_HeadPose_Yaw = value;
					this.SendPropertyChanged("FaceAttributes_HeadPose_Yaw");
					this.OnFaceAttributes_HeadPose_YawChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaceAttributes_HeadPose_Pitch", DbType="Float")]
		public System.Nullable<double> FaceAttributes_HeadPose_Pitch
		{
			get
			{
				return this._FaceAttributes_HeadPose_Pitch;
			}
			set
			{
				if ((this._FaceAttributes_HeadPose_Pitch != value))
				{
					this.OnFaceAttributes_HeadPose_PitchChanging(value);
					this.SendPropertyChanging();
					this._FaceAttributes_HeadPose_Pitch = value;
					this.SendPropertyChanged("FaceAttributes_HeadPose_Pitch");
					this.OnFaceAttributes_HeadPose_PitchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit")]
		public System.Nullable<bool> IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedAt", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedAt
		{
			get
			{
				return this._CreatedAt;
			}
			set
			{
				if ((this._CreatedAt != value))
				{
					this.OnCreatedAtChanging(value);
					this.SendPropertyChanging();
					this._CreatedAt = value;
					this.SendPropertyChanged("CreatedAt");
					this.OnCreatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedAt", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdatedAt
		{
			get
			{
				return this._UpdatedAt;
			}
			set
			{
				if ((this._UpdatedAt != value))
				{
					this.OnUpdatedAtChanging(value);
					this.SendPropertyChanging();
					this._UpdatedAt = value;
					this.SendPropertyChanged("UpdatedAt");
					this.OnUpdatedAtChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
