CREATE TABLE [RBApp].[PersonFaceInfo](
	[Id] bigint IDENTITY NOT NULL,
	[PersonId] [nvarchar](40) NOT NULL,
	[FaceConfidence] [nvarchar](40) NULL,
	[FaceRectangle_Width] float NULL,
	[FaceRectangle_Height] float NULL,
	[FaceRectangle_Left] float NULL,
	[FaceRectangle_Top] float NULL,
	[FaceLandmarks_PupilLeft_X] float NULL,
	[FaceLandmarks_PupilLeft_Y] float NULL,
	[FaceLandmarks_PupilRight_X] float NULL,
	[FaceLandmarks_PupilRight_Y] float NULL,
	[FaceLandmarks_NoseTip_X] float NULL,
	[FaceLandmarks_NoseTip_Y] float NULL,
	[FaceLandmarks_MouseLeft_X] float NULL,
	[FaceLandmarks_MouseLeft_Y] float NULL,
	[FaceLandmarks_MouseRight_X] float NULL,
	[FaceLandmarks_MouseRight_Y] float NULL,
	[FaceLandmarks_EyebrowLeftOuter_X] float NULL,
	[FaceLandmarks_EyebrowLeftOuter_Y] float NULL,
	[FaceLandmarks_EyebrowLeftInner_X] float NULL,
	[FaceLandmarks_EyebrowLeftInner_Y] float NULL,
	[FaceLandmarks_EyeLeftOuter_X] float NULL,
	[FaceLandmarks_EyeLeftOuter_Y] float NULL,
	[FaceLandmarks_EyeLeftTop_X] float NULL,
	[FaceLandmarks_EyeLeftTop_Y] float NULL,
	[FaceLandmarks_EyeLeftBottom_X] float NULL,
	[FaceLandmarks_EyeLeftBottom_Y] float NULL,
	[FaceLandmarks_EyeLeftInner_X] float NULL,
	[FaceLandmarks_EyeLeftInner_Y] float NULL,
	[FaceLandmarks_EyebrowRightInner_X] float NULL,
	[FaceLandmarks_EyebrowRightInner_Y] float NULL,
	[FaceLandmarks_EyebrowRightOuter_X] float NULL,
	[FaceLandmarks_EyebrowRightOuter_Y] float NULL,
	[FaceLandmarks_EyeRightInner_X] float NULL,
	[FaceLandmarks_EyeRightInner_Y] float NULL,
	[FaceLandmarks_EyeRightTop_X] float NULL,
	[FaceLandmarks_EyeRightTop_Y] float NULL,
	[FaceLandmarks_EyeRightBottom_X] float NULL,
	[FaceLandmarks_EyeRightBottom_Y] float NULL,
	[FaceLandmarks_EyeRightOuter_X] float NULL,
	[FaceLandmarks_EyeRightOuter_Y] float NULL,
	[FaceLandmarks_NoseRootLeft_X] float NULL,
	[FaceLandmarks_NoseRootLeft_Y] float NULL,
	[FaceLandmarks_NoseRootRight_X] float NULL,
	[FaceLandmarks_NoseRootRight_Y] float NULL,
	[FaceLandmarks_NoseLeftAlarTop_X] float NULL,
	[FaceLandmarks_NoseLeftAlarTop_Y] float NULL,
	[FaceLandmarks_NoseRightAlarTop_X] float NULL,
	[FaceLandmarks_NoseRightAlarTop_Y] float NULL,
	[FaceLandmarks_NoseLeftAlarOutTip_X] float NULL,
	[FaceLandmarks_NoseLeftAlarOutTip_Y] float NULL,
	[FaceLandmarks_NoseRightAlarOutTip_X] float NULL,
	[FaceLandmarks_NoseRightAlarOutTip_Y] float NULL,
	[FaceLandmarks_UpperLipTop_X] float NULL,
	[FaceLandmarks_UpperLipTop_Y] float NULL,
	[FaceLandmarks_UpperLipBottom_X] float NULL,
	[FaceLandmarks_UpperLipBottom_Y] float NULL,
	[FaceLandmarks_UnderLipTop_X] float NULL,
	[FaceLandmarks_UnderLipTop_Y] float NULL,
	[FaceLandmarks_UnderLipBottom_X] float NULL,
	[FaceLandmarks_UnderLipBottom_Y] float NULL,
	[FaceAttributes_Age] float NULL,
	[FaceAttributes_Gender] [nvarchar](10) NULL,
	[FaceAttributes_Smile] float NULL,
	[FaceAttributes_FacialHair_Moustache] float NULL,
	[FaceAttributes_FacialHair_Beard] float NULL,
	[FaceAttributes_FacialHair_Sideburns] float NULL,
	[FaceAttributes_Glasses] [nvarchar](20) NULL,
	[FaceAttributes_HeadPose_Roll] float NULL,
	[FaceAttributes_HeadPose_Yaw] float NULL,
	[FaceAttributes_HeadPose_Pitch] float NULL,
	[IsDeleted] BIT NULL,
	[CreatedAt] DATETIME NULL,
	[UpdatedAt] DATETIME NULL
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)
)

ALTER TABLE [RBApp].[PersonFaceInfo] ALTER COLUMN [PersonId] [nvarchar](255) NOT NULL;

GO
